/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import Model.*;
import Services.*;
import java.sql.SQLException;
import java.time.LocalDate;

/**
 *
 * @author benji
 */
public class EmployeeDashboard extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeInterface
     */
    
    private Employee employee;
    
    
    public EmployeeDashboard(Employee employee) {
        initComponents();
        this.employee=employee;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        hoursWorkedField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        generatePayslip = new javax.swing.JButton();
        back = new javax.swing.JButton();
        overtimeHoursField = new javax.swing.JTextField();
        changePassword = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Hours Worked:");

        jLabel2.setText("Overtime Hours :");

        hoursWorkedField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hoursWorkedFieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jLabel3.setText("EMPLOYEES DASHBOARD");

        generatePayslip.setText("Generate Payslip");
        generatePayslip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generatePayslipActionPerformed(evt);
            }
        });

        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        changePassword.setText("Change Password");
        changePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(hoursWorkedField, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(overtimeHoursField))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(generatePayslip, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(changePassword))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(hoursWorkedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(overtimeHoursField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(generatePayslip, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back)
                    .addComponent(changePassword))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hoursWorkedFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hoursWorkedFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hoursWorkedFieldActionPerformed

    private void generatePayslipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generatePayslipActionPerformed
        // TODO add your handling code here:
        Pattern numberPattern = Pattern.compile("^\\d+(\\.\\d{1,2})?$");
        
        
        if(employee==null){
         JOptionPane.showMessageDialog(this, "Session expired. Please log in again.");
           new LoginForm().setVisible(true);
         dispose();
          return;
        }
        else if(hoursWorkedField.getText().isBlank()){
            JOptionPane.showMessageDialog(null,"Please enter your hours worked");
            hoursWorkedField.requestFocusInWindow();
            return;
        }
        else if(!numberPattern.matcher(hoursWorkedField.getText()).matches()){
            JOptionPane.showMessageDialog(null, "Please enter valid numerical values only");
            hoursWorkedField.setText("");
            hoursWorkedField.requestFocusInWindow();
            return;
        }
        else if(overtimeHoursField.getText().isBlank()){
            JOptionPane.showMessageDialog(null,"Please enter overtime hours");
            overtimeHoursField.requestFocusInWindow();
        }
        else if(!numberPattern.matcher(overtimeHoursField.getText()).matches()){
            JOptionPane.showMessageDialog(null, "Please enter valid numerical values only");
            overtimeHoursField.setText("");
            overtimeHoursField.requestFocusInWindow();
            return;
        }
        else{
            
            Payroll payroll=new Payroll();
            double hoursWorked=Double.parseDouble(hoursWorkedField.getText().trim());
            double overtimeHours=Double.parseDouble(overtimeHoursField.getText().trim());
            
            payroll.setHoursWorked(hoursWorked);
            payroll.setOvertimeHours(overtimeHours);
            
             JobRoleService roleService=new JobRoleService();
             
            LocalDate currentDate=LocalDate.now();
          
       
          try{
              
            ///  System.out.println("DEBUG: employee jobRoleId = " + employee.getJobRoleId());

            JobRole role=roleService.getJobRoleRates(employee.getJobRoleId());
       
          //Payroll payroll=new Payroll(role.getHourlyRate(),role.getOvertimeRate());
          /// CompanyInfo companyInfo=new CompanyInfo();
           
           /*   if(role==null){
                  JOptionPane.showMessageDialog(this,"Job role rates not found","Error",JOptionPane.ERROR_MESSAGE);
                 
              return;
          }*/
              
                    roleService.generatePayslip(employee, role, payroll);
                    
                    System.out.println("Saving payroll for employee: " + employee.getID());

                    roleService.savePayroll(employee, payroll, currentDate.getMonth().toString(), role);
                  
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Database Error:"+e.getMessage());
        }
          
     
        }
      
    }//GEN-LAST:event_generatePayslipActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
      LoginForm login=new LoginForm();
      
      login.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void changePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordActionPerformed
        // TODO add your handling code here:
        EmployeePassword employeePassword=new EmployeePassword();
        
        employeePassword.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_changePasswordActionPerformed

    /**
     * @param args the command line arguments
     */
  /*  public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       /* try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeDashboard().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton changePassword;
    private javax.swing.JButton generatePayslip;
    private javax.swing.JTextField hoursWorkedField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField overtimeHoursField;
    // End of variables declaration//GEN-END:variables
}
