/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;
import Services.*;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author benji
 */
public class PayHistoryResults extends javax.swing.JFrame {

    /**
     * Creates new form PayHistoryResults
     */
    
    
    private String employeeId;
  
    public PayHistoryResults(String employeeId) {
        initComponents();
        this.employeeId=employeeId;
        loadPayHistory();
    }
    
public void loadPayHistory() {

    JobRoleService service = new JobRoleService();

    try {
        ResultSet rs = service.getPayrollHistory(employeeId);

        StringBuilder sb = new StringBuilder();
        sb.append("DATE\t\tHOURS\tOVERTIME\tNET PAY\n");
        sb.append("----------------------------------------------------------------------------------------------------------------------\n");

        boolean found = false;

        while (rs.next()) {
            found = true;
            sb.append(rs.getTimestamp("created_at")).append("\t")
              .append(rs.getDouble("hours_worked")).append("\t")
              .append(rs.getDouble("overtime_hours")).append("\t")
              .append("R").append(rs.getDouble("net_pay")).append("\n");
            
             resultsArea.setText(sb.toString());
        }

        if (!found) {
        
            
            JOptionPane.showMessageDialog(null,"No payslip history found for "+employeeId);
        }

       

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage());
    }
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        resultsArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        resultsArea.setColumns(20);
        resultsArea.setRows(5);
        jScrollPane1.setViewportView(resultsArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea resultsArea;
    // End of variables declaration//GEN-END:variables
}
